### ISSUE TITLE
When <src>/snippets directory does not exist -> stacktrace

### ISSUE THREAD

**Issue by uglow** [swanky-docs/swanky-server#57]
## Issue
In trying to debug a build error in my content, I renamed my `snippets` directory to `___snippets`. Re-running the build produced this stacktrace:

```
10% building modules 4/8 modules 4 active ...mes/confit-theme/js/libs/accordion.js/mydev/code/yo/generator-confit/node_modules/nunjucks/src/environment.js:498
                    if(err) { throw err; }
                              ^

Template render error: (unknown path) [Line 52, Column 88]
  Error: ENOENT: no such file or directory, scandir '/mydev/code/yo/generator-confit/docs/snippets'
    at Object.exports.prettifyError (/mydev/code/yo/generator-confit/node_modules/nunjucks/src/lib.js:34:15)
    at /mydev/code/yo/generator-confit/node_modules/nunjucks/src/environment.js:486:31
    at root [as rootRenderFunc] (eval at <anonymous> (/mydev/code/yo/generator-confit/node_modules/nunjucks/src/environment.js:565:24), <anonymous>:188:3)
    at Obj.extend.render (/mydev/code/yo/generator-confit/node_modules/nunjucks/src/environment.js:479:15)
    at Obj.extend.renderString (/mydev/code/yo/generator-confit/node_modules/nunjucks/src/environment.js:327:21)
    at Object.module.exports.renderString (/mydev/code/yo/generator-confit/node_modules/nunjucks/index.js:80:14)
    at compileContent (/mydev/code/yo/generator-confit/node_modules/swanky-server/src/tasks/getContent.js:133:21)
    at value.compiledContent.value.rawContent.map (/mydev/code/yo/generator-confit/node_modules/swanky-server/src/tasks/getContent.js:199:15)
    at Array.map (native)
    at page.compiledContent.page.fileDependencies.filter.reduce (/mydev/code/yo/generator-confit/node_modules/swanky-server/src/tasks/getContent.js:192:50)
    at Array.reduce (native)
    at addContent (/mydev/code/yo/generator-confit/node_modules/swanky-server/src/tasks/getContent.js:191:8)
    at async.each (/mydev/code/yo/generator-confit/node_modules/swanky-server/src/tasks/getContent.js:181:7)
    at /mydev/code/yo/generator-confit/node_modules/swanky-server/node_modules/async/dist/async.js:484:16
    at iteratorCallback (/mydev/code/yo/generator-confit/node_modules/swanky-server/node_modules/async/dist/async.js:1084:13)
    at /mydev/code/yo/generator-confit/node_modules/swanky-server/node_modules/async/dist/async.js:988:16
    at /mydev/code/yo/generator-confit/node_modules/swanky-server/node_modules/async/dist/async.js:484:16
    at iteratorCallback (/mydev/code/yo/generator-confit/node_modules/swanky-server/node_modules/async/dist/async.js:1084:13)
    at /mydev/code/yo/generator-confit/node_modules/swanky-server/node_modules/async/dist/async.js:988:16
    at fs.readFile (/mydev/code/yo/generator-confit/node_modules/swanky-server/src/tasks/getContent.js:172:15)
    at /mydev/code/yo/generator-confit/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
```

## Workaround
Creating an empty directory prevents the crash from occurring.

## Environment
Node 6.2.2
Swanky Server: 2.9.0

**Comment by rodleviton** [comment]
@uglow in theory this should not happen as https://github.com/swanky-docs/swanky-server/blob/8de07b7ef7a322f0cdb1b3966b8b0343cccf08f8/src/config/webpack/webpack.config.js#L122 will check if file exists before trying to load any snippets. I will try and re-create locally.

**Comment by rodleviton** [comment]
I guess the problem with untested theories are that they are just theories 🎱 . It looks like the webpack config was checking for the snippets folder to determine whether the `snippet.bootstrap.js` file should be loaded but... beyond that if a snippet is used in a non existent snippet is used in a template the compiler still tries to resolve and render it. I have put a check in place for this and will update in next release this weekend.
