### ISSUE TITLE
When `sections` is specified as empty array -> stacktrace

### ISSUE THREAD

**Issue by uglow** [swanky-docs/swanky-server#58]
## Issue
While trying to solve a build issue, I removed all of the sections from `swanky.config.yaml`:

```
title: generator-confit
repo: https://github.com/odecee/generator-confit.git
version: 0.0.0-semantically-released
src: docs
output: website
# serverPath will only be set when publishing the documentation
serverPath:

theme: docs/themes/confit-theme
snippets: docs/snippets

sections: []
```

This produced a stacktrace when building the site:
```
/mydev/code/yo/generator-confit/node_modules/swanky-server/src/tasks/getSectionsConfig.js:18
  }).reduce((acc, value) => acc.concat(value));
     ^

TypeError: Reduce of empty array with no initial value
    at Array.reduce (native)
    at Object.module.exports [as getSectionsConfig] (/mydev/code/yo/generator-confit/node_modules/swanky-server/src/tasks/getSectionsConfig.js:18:6)
    at module.exports (/mydev/code/yo/generator-confit/node_modules/swanky-server/src/config/webpack/webpack.config.js:14:33)
    at module.exports (/mydev/code/yo/generator-confit/node_modules/swanky-server/src/config/build/index.js:16:23)
    at Object.module.exports.buildConfig (/mydev/code/yo/generator-confit/node_modules/swanky-server/src/index.js:33:37)
    at Object.<anonymous> (/mydev/code/yo/generator-confit/config/docs/swanky.webpack.config.js:1:108)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at requireConfig (/mydev/code/yo/generator-confit/node_modules/webpack/bin/convert-argv.js:111:18)
    at /mydev/code/yo/generator-confit/node_modules/webpack/bin/convert-argv.js:124:17
    at Array.forEach (native)
```

## Workaround
Don't have an empty section.

## Environment
Node 6.2.2
Swanky Server 2.9.0

**Comment by rodleviton** [comment]
@uglow next release will provide a fallback section if none is defined e.g.

```
sections: []
```

This fallback will also cover the case when no `sections` key is defined at all within the `swanky.config` file.
